# Runs on every build (see the git_info target in CMakeLists.txt) and writes
# a header with the current commit / branch / dirty state. The file is only
# rewritten when its content changes, so an unchanged tree causes no rebuild.
#
# Inputs: -DSOURCE_DIR=<repo> -DOUT_FILE=<header path>

set(GIT_HASH "unknown")
set(GIT_BRANCH "unknown")
set(GIT_DIRTY 0)

find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE _hash OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND _hash)
    set(GIT_HASH "${_hash}")
  endif()

  execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE _branch OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND _branch)
    set(GIT_BRANCH "${_branch}")
  endif()

  # Tracked-file changes only; untracked files (runs/, build dirs) don't count.
  execute_process(COMMAND ${GIT_EXECUTABLE} status --porcelain --untracked-files=no
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND _status)
    set(GIT_DIRTY 1)
  endif()
endif()

set(_content
"/* Generated by cmake/GitInfo.cmake on every build. Do not edit. */
#define AERO_GIT_HASH \"${GIT_HASH}\"
#define AERO_GIT_BRANCH \"${GIT_BRANCH}\"
#define AERO_GIT_DIRTY ${GIT_DIRTY}
")

set(_old "")
if(EXISTS "${OUT_FILE}")
  file(READ "${OUT_FILE}" _old)
endif()
if(NOT _old STREQUAL _content)
  file(WRITE "${OUT_FILE}" "${_content}")
endif()
